name: Sync Fork

on:
  schedule:
    # 北京时间每天凌晨 0 点（UTC 时间前一天 16:00）
    - cron: '0 16 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # 获取完整的提交历史

      - name: Add upstream remote
        run: |
          git remote add upstream https://github.com/wzdnzd/aggregator.git
          git fetch upstream

      - name: Merge upstream changes
        run: |
          git checkout main # 确保你的默认分支是 main，如果是 master 请改为 master
          git merge upstream/main --allow-unrelated-histories
        continue-on-error: true # 如果有冲突，允许继续执行

      - name: Force push on conflict
        if: failure() # 仅在上一合并步骤失败时执行
        run: |
          git checkout main
          git reset --hard upstream/main
          git push origin main --force
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      - name: Push changes to fork
        if: success() # 仅在合并成功时执行
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
